kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  labels:
    env: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi