kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    env: dev
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"